const SIGN_IN = 'SIGN_IN';
const SIGN_OUT = 'SIGN_OUT';
const CREATE_STREAM = 'CREATE_STREAM';
const FETCH_STREAMS = 'FETCH_STREAMS';
const FETCH_STREAM = 'FETCH_STREAM';
const FETCH_VOD = 'FETCH_VOD';
const FETCH_VODS = 'FETCH_VODS';
const DELETE_STREAM = 'DELETE_STREAM';
const EDIT_STREAM = 'EDIT_STREAM';


export default { SIGN_IN, SIGN_OUT, CREATE_STREAM, FETCH_STREAM, FETCH_STREAMS, FETCH_VOD, FETCH_VODS, DELETE_STREAM, EDIT_STREAM }